name: hostify
description: ".Hostify - Property Management System"
publish_to: "none"
version: 1.1.2+6

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Firebase
  firebase_core: ^3.11.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  firebase_messaging: ^15.2.10

  # Supabase
  supabase_flutter: ^2.7.0

  # Navigation
  go_router: ^14.3.0

  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  provider: ^6.1.2

  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^7.0.2
  fl_chart: ^1.1.1
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.2
  table_calendar: ^3.2.0
  smooth_page_indicator: ^2.0.1
  carousel_slider: ^5.0.0

  # Utilities
  intl: ^0.20.2
  image_picker: ^1.1.2

  uuid: ^4.5.1
  equatable: ^2.0.5
  shared_preferences: ^2.3.3
  url_launcher: ^6.3.1
  http: ^1.2.0
  local_auth: ^2.1.8
  flutter_secure_storage: ^9.2.2
  icalendar_parser: ^1.0.0
  pdf: ^3.11.1
  printing: ^5.13.2
  path_provider: ^2.1.4
  timeago: ^3.7.0
  file_picker: ^8.1.4
  crypto: ^3.0.3
  share_plus: ^12.0.1
  flutter_local_notifications: ^18.0.1
  path: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.4.3
  build_runner: ^2.4.12
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - hostifyold/assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
